import 'package:instagramclone/models/reels_model.dart';

final List<Reels> reels = [
  Reels(
    "Shivam",
    "tujomila.mp4",
    "Tu jo Mila",
    "hloo guys",
    "35.6k",
    "12k",
    true,
    false,
    "shivina",
  ),
  Reels(
    "Tamanna",
    "dilkepass.mp4",
    "Har Pal dil ke Pass",
    "Favourite Song",
    "53.6k",
    "24k",
    true,
    true,
    "seema",
  ),
  Reels(
    "Raman",
    "ranjhana.mp4",
    "Ranjhana",
    "Like !! Comment",
    "43.9k",
    "17.5k",
    false,
    false,
    "Seema",
  ),
  // Reels(
  //   "yashu",
  //   "https://images.unsplash.com/photo-1650287621855-20aa9452f1f7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
  //   "wah Khudaya",
  //   "Tenu takiye je khalo ke..",
  //   "13.9k",
  //   "169",
  //   true,
  //   false,
  //   "tamanna",
  // ),
  // Reels(
  //   "Shivi",
  //   "https://images.unsplash.com/photo-1650288760766-a211b4a7c14f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
  //   "Jeena Bhool Jauga",
  //   "nyc lyrics",
  //   "55.6k",
  //   "18k",
  //   true,
  //   false,
  //   "shivam",
  // ),
  // Reels(
  //   "Raman",
  //   "",
  //   "Perfect",
  //   "Perfect Tonight",
  //   "35.6k",
  //   "12k",
  //   true,
  //   false,
  //   "shivina",
  // ),
  // Reels(
  //   "Seema",
  //   "https://images.unsplash.com/photo-1650292068299-3524ed138414?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
  //   "Life is beautiful",
  //   "nyc song",
  //   "5.6k",
  //   "1.5k",
  //   true,
  //   false,
  //   "Raman",
  // ),
  // Reels(
  //   "angel",
  //   "https://images.unsplash.com/photo-1650179745441-bc5f328d0d09?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
  //   "hawayien",
  //   "le jaye mujhe khan hawanyien",
  //   "15.4k",
  //   "2k",
  //   true,
  //   true,
  //   "shivi",
  // ),
];
